"""print(" ")
print("creando items")

mi_item = Item(nombre_item='Tomate',cantidad_item=3)
mi_item2 = Item(nombre_item='Lechuga',cantidad_item=5)
mi_item3 = Item(nombre_item='fideos',cantidad_item=8)
mi_item4 = Item(nombre_item='crema',cantidad_item=5)
mi_item5 = Item(nombre_item='champignon',cantidad_item=8)

print(" ")
print("agregando items")
mi_heladera = MiHeladera()
mi_heladera.add_item(mi_item)
mi_heladera.add_item(mi_item2)
mi_heladera.add_item(mi_item3)
mi_heladera.add_item(mi_item4)
mi_heladera.add_item(mi_item5)

print(" ")
print("creando receta")
mi_libro=MiLibroDeRecetas()
print(" ")
mi_receta= Receta("fideos con crema")
mi_receta.add_ingrediente(nombre_ingrediente='fideos',cantidad_ingrediente=1)
mi_receta.add_ingrediente(nombre_ingrediente='crema',cantidad_ingrediente=1)
mi_receta.add_ingrediente(nombre_ingrediente='champignon',cantidad_ingrediente=4)
mi_receta.add_ingrediente(nombre_ingrediente='cebolla de verdeo',cantidad_ingrediente=2)
mi_receta.add_ingrediente(nombre_ingrediente='queso rallado',cantidad_ingrediente=1)
print(" ")
print("guardando receta")
mi_libro.add_receta(mi_receta)
print(" ")
print("mostrar items de receta")
mi_receta.show_items()
print(" ")
print("usar receta")
mi_libro.use_receta("fideos con crema",mi_heladera)"""